export const prerequisites = [
  //? Obrigatórias
  { name: "Circuitos Digitais", preRequisites: [], type: "obr", profile: 1 },
  {
    name: "Geometria Analítica e Álgebra Linear",
    preRequisites: [],
    type: "obr",
    profile: 1,
  },
  {
    name: "Introdução à Programação",
    preRequisites: [],
    type: "obr",
    profile: 1,
  },
  {
    name: "Laboratório de Circuitos Digitais",
    preRequisites: [],
    type: "obr",
    profile: 1,
  },
  {
    name: "Laboratório de Programação",
    preRequisites: [],
    type: "obr",
    profile: 1,
  },
  { name: "Lógica Matemática", preRequisites: [], type: "obr", profile: 1 },
  {
    name: "Arquitetura e Organização de Computadores",
    preRequisites: ["Introdução à Programação"],
    type: "obr",
    profile: 2,
  },
  {
    name: "Cálculo Diferencial e Integral 1",
    preRequisites: [],
    type: "obr",
    profile: 2,
  },
  {
    name: "Estruturas de Dados",
    preRequisites: ["Introdução à Programação", "Laboratório de Programação"],
    type: "obr",
    profile: 2,
  },
  {
    name: "Física Geral 1",
    preRequisites: ["Co-requisito: Cálculo Diferencial e Integral 1"],
    type: "obr",
    profile: 2,
  },
  {
    name: "Matemática Discreta",
    preRequisites: ["Lógica Matemática"],
    type: "obr",
    profile: 2,
  },
  {
    name: "Cálculo Diferencial e Integral 2",
    preRequisites: ["Cálculo Diferencial e Integral 1"],
    type: "obr",
    profile: 3,
  },
  {
    name: "Estruturas de Dados Avançados",
    preRequisites: ["Estruturas de Dados"],
    type: "obr",
    profile: 3,
  },
  {
    name: "Introdução à Engenharia de Software",
    preRequisites: [],
    type: "obr",
    profile: 3,
  },
  {
    name: "Programação Orientada a Objetos",
    preRequisites: ["Estruturas de Dados"],
    type: "obr",
    profile: 3,
  },
  {
    name: "Sistemas Operacionais",
    preRequisites: [
      "Estruturas de Dados",
      "Arquitetura e Organização de Computadores",
    ],
    type: "obr",
    profile: 3,
  },
  {
    name: "Bancos de Dados",
    preRequisites: ["Estruturas de Dados"],
    type: "obr",
    profile: 4,
  },
  {
    name: "Engenharia de Software",
    preRequisites: ["Introdução à Engenharia de Software"],
    type: "obr",
    profile: 4,
  },
  {
    name: "Informática, Ética e Sociedade",
    preRequisites: [],
    type: "obr",
    profile: 4,
  },
  {
    name: "Organização e Recuperação da Informação",
    preRequisites: ["Estruturas de Dados Avançados"],
    type: "obr",
    profile: 4,
  },
  {
    name: "Probabilidade e Estatística",
    preRequisites: ["Cálculo Diferencial e Integral 1"],
    type: "obr",
    profile: 4,
  },
  {
    name: "Redes de Computadores",
    preRequisites: ["Sistemas Operacionais"],
    type: "obr",
    profile: 4,
  },
  {
    name: "Inteligência Artificial",
    preRequisites: ["Estruturas de Dados Avançados"],
    type: "obr",
    profile: 5,
  },
  {
    name: "Processamento Gráfico",
    preRequisites: [
      "Estruturas de Dados Avançados",
      "Geometria Analítica e Álgebra Linear",
    ],
    type: "obr",
    profile: 5,
  },
  {
    name: "Teoria da Computação",
    preRequisites: ["Matemática Discreta"],
    type: "obr",
    profile: 5,
  },
  {
    name: "Linguagens de Programação",
    preRequisites: ["Estruturas de Dados Avançados"],
    type: "obr",
    profile: 6,
  },
  {
    name: "Projeto e Análise de Algoritmos",
    preRequisites: ["Matemática Discreta", "Estruturas de Dados Avançados"],
    type: "obr",
    profile: 6,
  },
  {
    name: "Compiladores",
    preRequisites: ["Teoria da Computação", "Programação Orientada a Objetos"],
    type: "obr",
    profile: 6,
  },
  {
    name: "Pesquisa Acadêmica em Computação",
    preRequisites: [],
    type: "obr",
    profile: 8,
  },

  //? Optativas Grupo 1
  {
    name: "Física 1 Teórico Experimental",
    preRequisites: [],
    type: "opt 1",
    profile: 2,
  },
  { name: "Física Geral 3", preRequisites: [], type: "opt 1", profile: 3 },
  { name: "Empreendedorismo", preRequisites: [], type: "opt 1", profile: 4 },
  {
    name: "E-science",
    preRequisites: ["120 créditos cursados"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Introdução À Língua Brasileira De Sinais - Libras - Para Bacharelado",
    preRequisites: [],
    type: "opt 1",
    profile: 2,
  },
  {
    name: "Sustentabilidade em Computação",
    preRequisites: ["120 créditos cursados"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Fundamentos de Ensino do Pensamento Computacional",
    preRequisites: [],
    type: "opt 1",
    profile: 3,
  },
  {
    name: "Algoritmos em Grafos",
    preRequisites: ["Projeto e Análise de Algoritmos"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Laboratório de Arquitetura de Computadores",
    preRequisites: [
      "Laboratório de Circuitos Digitais",
      "Introdução à Programação",
    ],
    type: "opt 1",
    profile: 2,
  },
  {
    name: "Laboratório de Sistemas Operacionais",
    preRequisites: [
      "Arquitetura e Organização de Computadores",
      "Estruturas de Dados",
    ],
    type: "opt 1",
    profile: 4,
  },
  {
    name: "Pesquisa Operacional I",
    preRequisites: ["Geometria Analítica e Álgebra Linear"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Pesquisa Operacional II",
    preRequisites: ["Pesquisa Operacional I"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Teoria dos Grafos",
    preRequisites: ["Matemática Discreta", "Estruturas de Dados Avançados"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Cálculo Númerico",
    preRequisites: [
      "Cálculo Diferencial e Integral 1",
      "Geometria Analítica e Álgebra Linear",
      "Introdução à Programação",
    ],
    type: "opt 1",
    profile: 4,
  },
  {
    name: "Algoritmos Distribuídos",
    preRequisites: ["Matemática Discreta", "Redes de Computadores"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Análise de Agrupamento",
    preRequisites: [
      "Matemática Discreta",
      "Organização e Recuperação da Informação",
    ],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Aprendizado de Máquina",
    preRequisites: ["Probabilidade e Estatística", "Inteligência Artificial"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Avaliação Experimental em Projetos de Software",
    preRequisites: ["Engenharia de Software"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Computação em GPU",
    preRequisites: ["Arquitetura e Organização de Computadores"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Computação Gráfica",
    preRequisites: ["Processamento Gráfico"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Computação Paralela",
    preRequisites: ["Sistemas Operacionais"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Desenvolvimento Web",
    preRequisites: ["Engenharia de Software"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Gestão de Projetos e Qualidade de Software",
    preRequisites: ["Engenharia de Software"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Interação Humano-Computador",
    preRequisites: ["Engenharia de Software"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Introdução a Criptografia",
    preRequisites: ["Matemática Discreta", "Estruturas de Dados"],
    type: "opt 1",
    profile: 4,
  },
  {
    name: "Laboratório de Redes de Computadores",
    preRequisites: ["Redes de Computadores"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Laboratório de Compiladores",
    preRequisites: ["Compiladores"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Multimídia Computacional",
    preRequisites: ["Processamento Gráfico"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Novas Tecnologias em Banco de Dados",
    preRequisites: ["Bancos de Dados"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Processamento de Imagens",
    preRequisites: [
      "Geometria Analítica e Álgebra Linear",
      "Cálculo Diferencial e Integral 1",
    ],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Processamento de Linguagem Natural",
    preRequisites: ["Inteligência Artificial"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Processamento Massivo de Dados",
    preRequisites: ["120 créditos cursados"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Projeto e Desenvolvimento de Sistemas",
    preRequisites: ["Engenharia de Software", "Bancos de Dados"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Robótica",
    preRequisites: [
      "Estruturas de Dados Avançados",
      "Geometria Analítica e Álgebra Linear",
    ],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Segurança de Redes",
    preRequisites: [
      "Laboratório de Redes de Computadores",
      "Introdução a Criptografia",
    ],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Segurança e Auditoria de Sistemas",
    preRequisites: ["Introdução à Programação", "Redes de Computadores"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Sistemas de Banco de Dados",
    preRequisites: ["Bancos de Dados"],
    type: "opt 1",
    profile: 5,
  },
  {
    name: "Sistemas Distribuídos",
    preRequisites: ["Redes de Computadores"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Tópicos Avançados em Arquitetura de Computadores",
    preRequisites: ["Arquitetura e Organização de Computadores"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Tópicos Avançados em Banco de Dados",
    preRequisites: ["Bancos de Dados"],
    type: "opt 1",
    profile: 6,
  },
  {
    name: "Tópicos Avançados em Ciência da Computação",
    preRequisites: [],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Tópicos Avançados em Engenharia de Software",
    preRequisites: ["Engenharia de Software"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Tópicos Avançados em Linguagens de Programação",
    preRequisites: ["Linguagens de Programação"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Tópicos Avançados em Redes de Computadores e Sistemas Distribuídos",
    preRequisites: ["Redes de Computadores"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Tópicos Avançados em Sistemas Operacionais",
    preRequisites: ["Sistemas Operacionais"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Visão Computacional",
    preRequisites: ["Processamento Gráfico"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Tópicos Avançados em IA",
    preRequisites: ["Inteligência Artificial"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Tópicos Avançados em Processamento Gráfico",
    preReRequisites: ["Processamento Gráfico"],
    type: "opt 1",
    profile: 7,
  },
  {
    name: "Técnicas para a Construção de Software",
    preRequisites: ["Engenharia de Software"],
    type: "opt 1",
    profile: 5,
  },

  //? Conclusão de Curso
  {
    name: "Estágio Supervisionado 1",
    preRequisites: ["130 créditos cursados"],
    type: "conc",
    profile: 9,
  },
  {
    name: "Iniciação à Pesquisa",
    preRequisites: ["Carta de aceitação do orientador"],
    type: "conc",
    profile: 9,
  },
  {
    name: "Estágio Supervisionado 2",
    preRequisites: ["130 créditos cursados", "Seminários de Computação"],
    type: "conc",
    profile: 10,
  },
  {
    name: "Projeto de Pesquisa",
    preRequisites: [
      "130 créditos cursados",
      "carta de aceitação do orientador",
      "Seminários de Computação",
    ],
    type: "conc",
    profile: 9,
  },
  {
    name: "Seminários de Computação",
    preRequisites: ["Estágio Supervisionado 2", "Projeto de Pesquisa"],
    type: "conc",
    profile: 10,
  },
]
